export const styles = {
    topcontainer: {
      display: "flex",
      alignItems: "center",
      justifyContent: "space-between",
    },
    menusection: {
      display: "block",
      width: "100%",
    },
    menusection1: {
      display: "flex",
      width: "100%",
    },
    menusection2: {
      display: "flex",
      width: "100%",
      marginTop: "8px",
    },
    rect1: {
      background:
        "linear-gradient(180deg, rgba(79, 152, 248, 0.2) 0%, rgba(140, 77, 239, 0.2) 100%)",
      maxWidth: "105px",
      maxHeight: "105px",
      minWidth: "105px",
      minHeight: "105px",
      width: "100%",
      borderRadius: "16px",
      fontSize: "13px",
      fontWeigth: "600",
      cursor: "pointer",
      fontFamily: "SemiBold, Arial, sans-serif",
    },
    rect2: {
      background:
        "linear-gradient(180deg, rgba(235, 83, 191, 0.2) 0%, rgba(234, 90, 79, 0.2) 100%)",
      maxWidth: "105px",
      maxHeight: "105px",
      minWidth: "105px",
      minHeight: "105px",
      width: "100%",
      marginLeft: "8px",
      borderRadius: "16px",
      fontSize: "13px",
      fontWeigth: "600",
      cursor: "pointer",
      fontFamily: "SemiBold, Arial, sans-serif",
    },
    rect3: {
      background:
        "linear-gradient(180deg, rgba(143, 91, 238, 0.2) 0%, rgba(234, 75, 226, 0.2) 100%)",
      maxWidth: "105px",
      maxHeight: "105px",
      minWidth: "105px",
      minHeight: "105px",
      width: "100%",
      borderRadius: "16px",
      fontSize: "13px",
      fontWeigth: "600",
      cursor: "pointer",
      fontFamily: "SemiBold, Arial, sans-serif",
    },
    rect4: {
      background:
        "linear-gradient(180deg, rgba(231, 99, 139, 0.2) 0%, rgba(242, 166, 75, 0.2) 100%)",
      maxWidth: "105px",
      maxHeight: "105px",
      minWidth: "105px",
      minHeight: "105px",
      width: "100%",
      marginLeft: "8px",
      borderRadius: "16px",
      fontSize: "13px",
      fontWeigth: "600",
      cursor: "pointer",
      fontFamily: "SemiBold, Arial, sans-serif",
    },
    Icon1: {
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: "8px",
      background: "linear-gradient(180deg, #4F98F8 0%, #8C4DEF 100%)",
      width: "30px",
      height: "30px",
      marginBottom: "25px",
      cursor: "pointer",
    },
    Icon2: {
      background: "linear-gradient(180deg, #EB53BF 0%, #EA5A4F 100%)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: "8px",
      width: "30px",
      height: "30px",
      marginBottom: "25px",
      cursor: "pointer",
    },
    Icon3: {
      background: "linear-gradient(180deg, #8F5BEE 0%, #EA4BE2 100%)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: "8px",
      width: "30px",
      height: "30px",
      marginBottom: "25px",
      cursor: "pointer",
    },
    Icon4: {
      background: "linear-gradient(180deg, #E7638B 0%, #F2A64B 100%)",
      display: "flex",
      alignItems: "center",
      justifyContent: "center",
      borderRadius: "8px",
      width: "30px",
      height: "30px",
      marginBottom: "25px",
      cursor: "pointer",
    },
    rectContainer: {
      margin: "12px",
      cursor: "pointer",
    },
  };