import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "../components/styles.css";
import { Toaster } from "@/components/ui/sonner";
import { Provider } from "@/components/layout/provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-black no-scroll`}>
        <Provider>{children}</Provider>
        <Toaster className="bg-white" />
      </body>
    </html>
  );
}