import type { Metadata } from "next";
import { Navbar, Sidebar } from "@/components/layout";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="relative">
      <Navbar />
      <div className="flex">
        <Sidebar />
        <section className="flex flex-col flex-1 px-6 sm:px-14 pt-28 pb-6 max-md:pb-14 min-h-screen">
          <div className="w-full">{children}</div>
        </section>
      </div>
    </main>
  );
}
