import { Navbar } from "@/components/layout/asset-gen";
import type { Metadata } from "next";
import "../../components/styles.css";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <main className="bg-[#28272c]">
      <Navbar />
      {children}
    </main>
  );
}
